config/routes.rb
Rails.application.routes.draw do

  root 'efc#index'

  resources :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, presence: true

	def self.search(search)
		where("name like :name or note like :note", {name: "%#{search}%", note: "%#{search}%"})
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	protect_from_forgery with: :exception

	def index
		@contacts = Contact.all
		if params[:key]
			@contacts = Contact.search(params[:key]).order(id: :desc)
		else
			@contacts = Contact.all.order(id: :desc)
		end
	end

	def show
		@contact = Contact.find_by(id: params[:id])
	end

	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(contact_params)
		if @contact.valid?
			@contact.save
			redirect_to @contact
		else
			render :new
		end
	end

	private
	def contact_params
		params.require(:contact).permit(:name, :email, :phone, :note)
	end
end

app/controllers/efc_controller.rb
class EfcController < ApplicationController

	def index

	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/index.html.erb
<%= form_tag({:controller => "contacts", :action => "index"}, :method => "get") do %>
  <%= label_tag(:key, "Search for:") %>
  <%= text_field_tag(:key) %>
  <%= submit_tag("Search") %>
<% end %>

<% @contacts.each { |contact| %>
	<%= contact.id %>, <%= contact.name %>, <%= contact.email %>, <%= contact.phone %>, <%= contact.note %>
	<br>
<% } %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>


  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(@contact.errors.count, "error") %> prohibited
        this contact from being saved:
      </h3>
      <ul>
        <% @contact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for :contact, url: contacts_path do |f| %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :email  %>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :phone  %>
		<%= f.text_field :phone %>
	</p>
	<p>
		<%= f.label :note  %>
		<%= f.text_area :note, size: "80x5" %>
	</p>

	<%= f.submit %>

<% end %>

app/views/contacts/show.html.erb
<% if !@contact.nil? %>
<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Note:</strong>
  <%= @contact.note %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Elite Fitness Club</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>  
  <link href="https://fonts.googleapis.com/css?family=Changa|Nunito" rel="stylesheet" type='text/css'>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body class="body" ng-app="efc">

<%= yield %>

  <%= javascript_include_tag 'efc' %>
</body>
</html>